apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: atlantis
  annotations:
    configmap.reloader.stakater.com/reload: 'ngrok-trigger'
  labels:
    app: ngrok
spec:
  selector:
    matchLabels:
      app: ngrok
  replicas: 1
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok:3
          imagePullPolicy: Always
          args: ['http', 'atlantis:80']
          ports:
            - containerPort: 4040
          env:
          - name: NGROK_AUTHTOKEN
            valueFrom:
              secretKeyRef:
                name: k3d-ngrok
                key: NGROK_AUTHTOKEN
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
