# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx
#   namespace: default
#   labels:
#     app.kubernetes.io/name: nginx
#     app.kubernetes.io/instance: nginx
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
# spec:
#   rules:
#     - host: example.com
#       http:
#         paths:
#           - path: /
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: nginx
#                 port:
#                   name: http
#   tls:
#   - hosts:
#     - example.com
#     secretName: apex-tls
