apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# To upgrade ArgoCD, increment the version here
# https://github.com/argoproj/argo-cd/tags
resources:
  - https://github.com/argoproj/argo-cd.git/manifests/ha/cluster-install?ref=v2.6.4&timeout=90s
  - argocd-namespace.yaml
  - argocd-ui-ingress.yaml
  - argocd-ui-ingressroute.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-rbac-cm.yaml

generatorOptions:
  disableNameSuffixHash: true
