apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preprod-ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: preprod
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.5.2
    helm:
      values: |-
        controller:
          ingressClass: nginx-preprod
          publishService:
            enabled: true
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
              service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          extraArgs:
            enable-ssl-passthrough: true
    chart: ingress-nginx
  destination:
    server: https://212.2.244.151:6443 # todo replace
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
