apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml
  - rbac.yaml

images:
  - name: kubefirst/kubernetes-toolkit
    newName: eb129/kubernetes-toolkit
    newTag: 'v0'

generatorOptions:
  disableNameSuffixHash: true
